package com.springboot.pojo;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * Date: Wed Sep 11 16:04:39 CST 2019.
 *
 * @author (lsy)
 */

public class UserPosition implements Serializable {


	private static final long serialVersionUID =  8014475283356463393L;


	/**
	 *   
	 */
    
	private Integer id;

	/**
	 *   
	 */
    
	private String city;

	/**
	 *   
	 */
    
	private String position;

	/**
	 *   
	 */
    
	private Double longitude;

	/**
	 *   
	 */
    
	private Double latitude;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

}
