package com.springboot.pojo;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * Date: Tue Sep 10 14:00:03 CST 2019.
 *
 * @author (lsy)
 */

public class Users  implements Serializable {


	private static final long serialVersionUID =  2747410668161865215L;


	/**
	 *   
	 */
    
	private Integer id;

	/**
	 *   
	 */
    
	private String username;

	/**
	 *   
	 */
    
	private Integer age;

	/**
	 *   
	 */
    
	private Integer phone;

	/**
	 *   
	 */
    
	private String email;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
